# Generated by Django 6.0 on 2026-01-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pdfupload_current_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasscodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_reset_at', models.DateTimeField(auto_now=True)),
                ('passcode_attempts', models.IntegerField(default=0)),
                ('passcode_locked_until', models.DateTimeField(blank=True, null=True)),
                ('creds_attempts', models.IntegerField(default=0)),
                ('creds_locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Passcode Configuration',
                'verbose_name_plural': 'Passcode Configuration',
            },
        ),
    ]
