# Generated by Django 6.0 on 2026-03-08 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passcodeconfig_passcode_configured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='uploaded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
